name: build and test
on:
  push:
    branches:
      - main

jobs:
  ci-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Install dependencies
        run: npm install

      - name: Install Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Pipx
        run: python3 -m pip install --user pipx

      - name: Ensure Pipx is on PATH
        run: python3 -m pipx ensurepath

      - name: Install Algokit
        run: pipx install algokit

      - name: Start local Algorand network
        run: algokit localnet start

      - name: Build contracts and test
        run: npm test
